### ISSUE TITLE
Correctly handle output if _JAVA_OPTIONS defined

### ISSUE THREAD

**Issue by CAMOBAP** [sshaw/ruby-jing#4] opened 2022-06-20 20:09 UTC
### Problem

When `_JAVA_OPTIONS` environment is defined, java prints a message:
`
 Picked up _JAVA_OPTIONS: ...
`

As result [`ExecutionError` is thrown](https://github.com/sshaw/ruby-jing/blob/master/lib/jing.rb#L93)

Per https://superuser.com/questions/585695/suppressing-the-picked-up-java-options-message there is no way to suppress it, so 

### Proposed solution

I think the only way to handle it in the scope of [`parse_output`](https://github.com/sshaw/ruby-jing/blob/master/lib/jing.rb#L129)

**Comment by sshaw** [comment] 2022-06-20 20:24
Hi, thanks for bringing this to my attention

> Proposed solution
> I think the only way to handle it in the scope of [parse_output](https://github.com/sshaw/ruby-jing/blob/master/lib/jing.rb?rgh-link-date=2022-06-20T20%3A09%3A37Z#L129)

That makes sense but I wonder if I did this because Jing and/or Java could exit success but there is still an underlying error? A non-schema-related error that would not be detected by `parse_output`? 

Though I suppose even if this was true, we could filter out `Picked up _JAVA_OPTIONS ...` from `out` and if there's still something there yet no Jing-related errors raise `ExecutionException`?

**Comment by sshaw** [comment] 2022-06-20 20:26
> if I did this because Jing and/or Java could exit success but there is still an underlying error?
> ...
> Though I suppose even if this was true, we could filter out

Ideally we just rely on `$?.success?` and do not filter out `Picked up _JAVA_OPTIONS ...`. If there's way to confirm `$?.success?` is reliable then great. 

I could very well just be tainted by these youngsters with their Node.js command-line programs that `exit(0)` on error! 👴

**Comment by CAMOBAP** [comment] 2022-06-20 20:29
> That makes sense but I wonder if I did this because Jing and/or Java could exit success but there is still an underlying error?

There is no actual error, this message is more like diagnostic information from JVM

> Ideally we just rely on $?.success?

As far as I understand we still can/should rely on it, `ExecutionError` happens because `error.none?` is true while `out.empty?` is false

**Comment by sshaw** [comment] 2022-06-20 21:05
>> That makes sense but I wonder if I did this because Jing and/or Java could exit success but there is still an underlying error?

> There is no actual error, this message is more like diagnostic information from JVM

Yes I understand. 

> As far as I understand we still can/should rely on it, ExecutionError happens because error.none? is true while out.empty? is false

In other scenarios this may not be this case which is why I _thought_ I may be checking `error.none? && out.empty?`

But I think we can assume that ` $?.success?` works as intended (i.e., JVM is not exiting success when there's really an error) and use your proposed solution.

**Comment by sshaw** [comment] 2022-06-23 02:43
Fixed via #5

**Closed by sshaw** 2022-06-23 02:43 UTC
